daemon:
  interval: 30s
scanners:
  - host: google.com
    startPort: 75
    endPort: 85
    networks:
      - tcp
    timeout: 5s
  - host: localhost
    startPort: 8080
    endPort: 8083
    networks:
      - tcp
observers:
  onChange:
    - notify:
        smtp:
          from: from@example.com
          password: 123
          to: to@example.com
          smtpHost: example.com
          smtpPort: 587