daemon:
  cron: "*/1 * * * *"
scanners:
  - host: localhost
  # - cidr: "127.0.0.0/8"
    startPort: 3000
    endPort: 3003
    timeout: 3s
    protocol: tcp
observers:
  onChange:
    - notify:
        file:
          output: ./results.txt